name: passing_arguments

on: 
    push:
        branches: passing_arguments_to_an_action

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: initial
              run: |
                "ls -a"
                "java -version"
            - name: Step one
              uses: actions/checkout@v2
              with:
                repository: apache/tomcat
                ref: master
                path: ./tomcat
            - name: Step two
              uses: actions/setup-java@v1
              with:
                  java-version: '9.0.4'
                  java-package: jdk
                  architecture: x64
            
            - name: Step two
              run: |
                "ls -al"
                "java -version"
                
